//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalci
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
        public int ID { get; set; }
        public Nullable<double> firstnumber { get; set; }
        public Nullable<double> secondnumber { get; set; }
        public Nullable<double> result { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
